FROM tiangolo/uwsgi-nginx:python3.6

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    curl \
	git \
	python3 \
	python3-dev \
	python3-setuptools \
	python3-pip \
	nginx \
    postgresql \
    python-psycopg2 \
    libpq-dev \
	supervisor && \
	pip3 install -U pip setuptools && \
   rm -rf /var/lib/apt/lists/*



RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y unzip xvfb libxi6 libgconf-2-4 \
    vim

RUN echo "deb http://nginx.org/packages/mainline/ubuntu/ wily nginx" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62
RUN apt-get update && apt-get install -y --force-yes nginx
