version: '3'

services:
    db:
        image: healthcheck/postgres
        environment:
            POSTGRES_USER: testuser
            POSTGRES_DB: test
            POSTGRES_PASSWORD: testuser
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "cf_web_app"
        ports:
        - "8080:80"
        volumes:
        - .:/home/code
        links:
        - db
        depends_on:
        - db
        environment:
        - APP_SETTINGS=config.DevelopmentConfig
        - DATABASE_URL=postgresql://testuser:testuser@db/cf_app
        - CREDENTIALS_SALT=1111111111111111
        - CREDENTIALS_SECRET=1111111111111111
        - SECRET_KEY=1111111111111111
        - PYTHONUNBUFFERED=1
